package sx127x

const (
	// Register names (LoRa mode)
	REG_00_FIFO                    = 0x00
	REG_01_OP_MODE                 = 0x01
	REG_06_FRF_MSB                 = 0x06
	REG_07_FRF_MID                 = 0x07
	REG_08_FRF_LSB                 = 0x08
	REG_09_PA_CONFIG               = 0x09
	REG_0A_PA_RAMP                 = 0x0A
	REG_0B_OCP                     = 0x0B
	REG_0C_LNA                     = 0x0C
	REG_0D_FIFO_ADDR_PTR           = 0x0D
	REG_0E_FIFO_TX_BASE_ADDR       = 0x0E
	REG_0F_FIFO_RX_BASE_ADDR       = 0x0F
	REG_10_FIFO_RX_CURRENT_ADDR    = 0x10
	REG_11_IRQ_FLAGS_MASK          = 0x11
	REG_12_IRQ_FLAGS               = 0x12
	REG_13_RX_NB_BYTES             = 0x13
	REG_14_RX_HEADER_CNT_VALUE_MSB = 0x14
	REG_15_RX_HEADER_CNT_VALUE_LSB = 0x15
	REG_16_RX_PACKET_CNT_VALUE_MSB = 0x16
	REG_17_RX_PACKET_CNT_VALUE_LSB = 0x17
	REG_18_MODEM_STAT              = 0x18
	REG_19_PKT_SNR_VALUE           = 0x19
	REG_1A_PKT_RSSI_VALUE          = 0x1A
	REG_1B_RSSI_VALUE              = 0x1B
	REG_1C_HOP_CHANNEL             = 0x1C
	REG_1D_MODEM_CONFIG1           = 0x1D
	REG_1E_MODEM_CONFIG2           = 0x1E
	REG_1F_SYMB_TIMEOUT_LSB        = 0x1F
	REG_20_PREAMBLE_MSB            = 0x20
	REG_21_PREAMBLE_LSB            = 0x21
	REG_22_PAYLOAD_LENGTH          = 0x22
	REG_23_MAX_PAYLOAD_LENGTH      = 0x23
	REG_24_HOP_PERIOD              = 0x24
	REG_25_FIFO_RX_BYTE_ADDR       = 0x25
	REG_26_MODEM_CONFIG3           = 0x26
	REG_2F_IF_FREQ2                = 0x2F
	REG_30_IF_FREQ1                = 0x30
	REG_31_DETECTION_OPTIMIZE      = 0x31
	REG_36_HIGHBW_OPTIMIZE1        = 0x36
	REG_37_DETECTION_THRESHOLD     = 0x37
	REG_3A_HIGHBW_OPTIMIZE2        = 0x3A
	REG_40_DIO_MAPPING1            = 0x40
	REG_41_DIO_MAPPING2            = 0x41
	REG_42_VERSION                 = 0x42
	REG_4B_TCXO                    = 0x4B
	REG_4D_PA_DAC                  = 0x4D
	REG_5B_FORMER_TEMP             = 0x5B
	REG_61_AGC_REF                 = 0x61
	REG_62_AGC_THRESH1             = 0x62
	REG_63_AGC_THRESH2             = 0x63
	REG_64_AGC_THRESH3             = 0x64
)

const (
	REG_01_OP_MODE_MODE_OFFSET = 0
	REG_01_OP_MODE_MODE_WIDTH  = 3
	REG_01_OP_MODE_MODE_MASK   = (1<<REG_01_OP_MODE_MODE_WIDTH - 1)

	REG_01_OP_MODE_LFM_OFFSET = 3
	REG_01_OP_MODE_LFM_WIDTH  = 1
	REG_01_OP_MODE_LFM_MASK   = (1<<REG_01_OP_MODE_LFM_WIDTH - 1)

	REG_01_OP_MODE_LRM_OFFSET = 7
	REG_01_OP_MODE_LRM_WIDTH  = 1
	REG_01_OP_MODE_LRM_MASK   = (1<<REG_01_OP_MODE_LRM_WIDTH - 1)

	REG_09_PA_CONFIG_POWER_OFFSET = 0
	REG_09_PA_CONFIG_POWER_WIDTH  = 4
	REG_09_PA_CONFIG_POWER_MASK   = (1<<REG_09_PA_CONFIG_POWER_WIDTH - 1)

	REG_09_PA_CONFIG_MAX_POWER_OFFSET = 4
	REG_09_PA_CONFIG_MAX_POWER_WIDTH  = 3
	REG_09_PA_CONFIG_MAX_POWER_MASK   = (1<<REG_09_PA_CONFIG_MAX_POWER_WIDTH - 1)

	REG_09_PA_CONFIG_SELECT_OFFSET = 7
	REG_09_PA_CONFIG_SELECT_WIDTH  = 1
	REG_09_PA_CONFIG_SELECT_MASK   = (1<<REG_09_PA_CONFIG_SELECT_WIDTH - 1)

	REG_12_IRQ_FLAGS_CAD_DETECTED_OFFSET = 0
	REG_12_IRQ_FLAGS_CAD_DETECTED_WIDTH  = 1
	REG_12_IRQ_FLAGS_CAD_DETECTED_MASK   = (1<<REG_12_IRQ_FLAGS_CAD_DETECTED_WIDTH - 1)

	REG_12_IRQ_FLAGS_FHSS_CHANGE_CHANNEL_OFFSET = 1
	REG_12_IRQ_FLAGS_FHSS_CHANGE_CHANNEL_WIDTH  = 1
	REG_12_IRQ_FLAGS_FHSS_CHANGE_CHANNEL_MASK   = (1<<REG_12_IRQ_FLAGS_FHSS_CHANGE_CHANNEL_WIDTH - 1)

	REG_12_IRQ_FLAGS_CAD_DONE_OFFSET = 2
	REG_12_IRQ_FLAGS_CAD_DONE_WIDTH  = 1
	REG_12_IRQ_FLAGS_CAD_DONE_MASK   = (1<<REG_12_IRQ_FLAGS_CAD_DONE_WIDTH - 1)

	REG_12_IRQ_FLAGS_TXDONE_OFFSET = 3
	REG_12_IRQ_FLAGS_TXDONE_WIDTH  = 1
	REG_12_IRQ_FLAGS_TXDONE_MASK   = (1<<REG_12_IRQ_FLAGS_TXDONE_WIDTH - 1)

	REG_12_IRQ_FLAGS_VALID_HEADER_OFFSET = 4
	REG_12_IRQ_FLAGS_VALID_HEADER_WIDTH  = 1
	REG_12_IRQ_FLAGS_VALID_HEADER_MASK   = (1<<REG_12_IRQ_FLAGS_VALID_HEADER_WIDTH - 1)

	REG_12_IRQ_FLAGS_PAYLOAD_CRC_ERR_OFFSET = 5
	REG_12_IRQ_FLAGS_PAYLOAD_CRC_ERR_WIDTH  = 1
	REG_12_IRQ_FLAGS_PAYLOAD_CRC_ERR_MASK   = (1<<REG_12_IRQ_FLAGS_PAYLOAD_CRC_ERR_WIDTH - 1)

	REG_12_IRQ_FLAGS_RXDONE_OFFSET = 6
	REG_12_IRQ_FLAGS_RXDONE_WIDTH  = 1
	REG_12_IRQ_FLAGS_RXDONE_MASK   = (1<<REG_12_IRQ_FLAGS_RXTIMEOUT_WIDTH - 1)

	REG_12_IRQ_FLAGS_RXTIMEOUT_OFFSET = 7
	REG_12_IRQ_FLAGS_RXTIMEOUT_WIDTH  = 1
	REG_12_IRQ_FLAGS_RXTIMEOUT_MASK   = (1<<REG_12_IRQ_FLAGS_RXTIMEOUT_WIDTH - 1)

	REG_1C_HOP_CHANNEL_CRC_ON_PAYLOAD_OFFSET = 6
	REG_1C_HOP_CHANNEL_CRC_ON_PAYLOAD_WIDTH  = 1
	REG_1C_HOP_CHANNEL_CRC_ON_PAYLOAD_MASK   = (1<<REG_1C_HOP_CHANNEL_CRC_ON_PAYLOAD_WIDTH - 1)

	REG_1D_MODEM_CONFIG1_CR_OFFSET = 1
	REG_1D_MODEM_CONFIG1_CR_WIDTH  = 3
	REG_1D_MODEM_CONFIG1_CR_MASK   = (1<<REG_1D_MODEM_CONFIG1_CR_WIDTH - 1)

	REG_1D_MODEM_CONFIG1_BW_OFFSET = 4
	REG_1D_MODEM_CONFIG1_BW_WIDTH  = 4
	REG_1D_MODEM_CONFIG1_BW_MASK   = (1<<REG_1D_MODEM_CONFIG1_BW_WIDTH - 1)

	REG_1E_MODEM_CONFIG2_CRC_OFFSET = 2
	REG_1E_MODEM_CONFIG2_CRC_WIDTH  = 1
	REG_1E_MODEM_CONFIG2_CRC_MASK   = (1<<REG_1E_MODEM_CONFIG2_CRC_WIDTH - 1)

	REG_1E_MODEM_CONFIG2_SF_OFFSET = 4
	REG_1E_MODEM_CONFIG2_SF_WIDTH  = 4
	REG_1E_MODEM_CONFIG2_SF_MASK   = (1<<REG_1E_MODEM_CONFIG2_SF_WIDTH - 1)

	REG_1E_MODEM_CONFIG2_SYMB_TIMEOUT_MSB_OFFSET = 0
	REG_1E_MODEM_CONFIG2_SYMB_TIMEOUT_MSB_WIDTH  = 2
	REG_1E_MODEM_CONFIG2_SYMB_TIMEOUT_MSB_MASK   = (1<<REG_1E_MODEM_CONFIG2_SYMB_TIMEOUT_MSB_WIDTH - 1)

	REG_26_MODEM_CONFIG3_AUTO_AGC_OFFSET = 2
	REG_26_MODEM_CONFIG3_AUTO_AGC_WIDTH  = 1
	REG_26_MODEM_CONFIG3_AUTO_AGC_MASK   = (1<<REG_26_MODEM_CONFIG3_AUTO_AGC_WIDTH - 1)

	REG_31_DETECTION_OPTIMIZE_SF_OFFSET = 0
	REG_31_DETECTION_OPTIMIZE_SF_WIDTH  = 3
	REG_31_DETECTION_OPTIMIZE_SF_MASK   = (1<<REG_31_DETECTION_OPTIMIZE_SF_WIDTH - 1)

	REG_31_DETECTION_OPTIMIZE_AUTOIFON_OFFSET = 7
	REG_31_DETECTION_OPTIMIZE_AUTOIFON_WIDTH  = 1
	REG_31_DETECTION_OPTIMIZE_AUTOIFON_MASK   = (1<<REG_31_DETECTION_OPTIMIZE_AUTOIFON_WIDTH - 1)

	REG_40_DIO_MAPPING1_OFFSET = 6
	REG_40_DIO_MAPPING1_WIDTH  = 2
	REG_40_DIO_MAPPING1_MASK   = (1<<REG_40_DIO_MAPPING1_WIDTH - 1)

	REG_4D_PA_DAC_BOOST_OFFSET = 0
	REG_4D_PA_DAC_BOOST_WIDTH  = 3
	REG_4D_PA_DAC_BOOST_MASK   = (1<<REG_4D_PA_DAC_BOOST_WIDTH - 1)
)

const (
	PA_DAC_DISABLE = 0x04
	PA_DAC_ENABLE  = 0x07

	// FXOSC is the crystal oscillator frequency of the module
	FXOSC = 32000000

	// FSTEP is the frequency synthesizer step = RH_RF95_FXOSC / 2^^19
	FSTEP = FXOSC / 524288
)

const (
	OP_MODE_SLEEP         = 0b000
	OP_MODE_STANDBY       = 0b001
	OP_MODE_FS_TX         = 0b010
	OP_MODE_TX            = 0b011
	OP_MODE_FS_RX         = 0b100
	OP_MODE_RX_CONTINUOUS = 0b101
	OP_MODE_RX_SINGLE     = 0b110
	OP_MODE_CAD           = 0b111
)

const (
	IRQ_CAD_DETECTED        = 1 << 0
	IRQ_FHSS_CHANGE_CHANNEL = 1 << 1
	IRQ_CAD_DONE            = 1 << 2
	IRQ_TX_DONE             = 1 << 3
	IRQ_VALID_HEADER        = 1 << 4
	IRQ_PAYLOAD_CRC_ERROR   = 1 << 5
	IRQ_RX_DONE             = 1 << 6
	IRQ_RX_TIMEOUT          = 1 << 7
)
